// Generated by CoffeeScript 1.9.0
var Shop, express, router;

express = require('express');

Shop = require('../models/shop');

router = express.Router();

router.get('/', function(req, res, next) {
  return Shop.select(function(err, result) {
    if (err) {
      return next(err);
    }
    return res.json(result);
  });
});

router.post('/', function(req, res, next) {
  return Shop.create(req.body, function(err, result) {
    if (err) {
      return next(err);
    }
    return res.json(result);
  });
});

router.get('/:id', function(req, res, next) {
  return Shop.get(req.params.id, function(err, result) {
    if (err) {
      return next(err);
    }
    return res.json(result);
  });
});

router.put('/:id', function(req, res) {
  return res.json(Shop.update(req.body));
});

router["delete"]('/:id', function(req, res) {
  return res.json(Shop["delete"](req.params.id));
});

module.exports = router;
