// Generated by CoffeeScript 1.9.0
var BaseModel;

BaseModel = (function() {
  function BaseModel(options) {
    if (options) {
      this.id = options.id;
    }
  }

  return BaseModel;

})();

module.exports = BaseModel;
